
spring:
    application:
        name: testDB
    datasource:
        url: jdbc:mysql://localhost:3306/my_test?serverTimezone=UTC&useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
        username: root
        password: A12a34s56@2022!@#
        driver-class-name: com.mysql.cj.jdbc.Driver
server:
    port: 9001
mybatis:
    mapper-locations: classpath:mapper/**/*.xml